version: '2'
services:
#---WEBSIG-------------------------------------
  lizmap:
    image: jancelin/geopoppy:lizmap-3.1.1
    restart: always
    ports:
     - 80:80
     - 443:443
    volumes:
     - /home/GeoPoppy/lizmap/project:/home
     - /home/GeoPoppy/lizmap/project/var:/var/www/websig/lizmap/var
     - /home/GeoPoppy/lizmap/project/tmp:/tmp
    links:
     - qgiserver:qgiserver
    networks:
      default:
        ipv4_address: 172.18.0.5
##Pensez à changer l'URL WMS dans le back-office de lizmap: http://qgiserver/cgi-bin/qgis_mapserv.fcgi

  qgiserver:
    image: jancelin/geopoppy:qgis-server2.14LTR-0.2
    restart: always
    volumes:
      - /home/GeoPoppy/lizmap/project:/home
    expose:
      - 80
    networks:
      default:
        ipv4_address: 172.18.0.7

#---Bases de données----------------------------------
  postgis:
    image: jancelin/geopoppy:postgis
    restart: always
    ports:
     - "5432:5432"
    volumes:
     - "/home/GeoPoppy/postgres_data:/var/lib/postgresql"
    networks:
      default:
        ipv4_address: 172.18.0.4

#---Outils--------------------------------------------
  portainer:
    image: portainer/portainer:linux-arm
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      default:
        ipv4_address: 172.18.0.2


  pgadmin4:
    image: jancelin/geopoppy:pgadmin4-beta1
    ports:
     - "5050:5050"
    volumes:
    #--ne pas oublier de créer le dossier:  mkdir /home/GeoPoppy/pgadmin4/pgadmin_data
     - "/home/GeoPoppy/pgadmin4/pgadmin_data:/pgadmin"
    networks:
      default:
        ipv4_address: 172.18.0.6
  cloud:
    image: valentinalexeev/rpi-cloudcmd
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ~:/root
      - /:/mnt/fs
    networks:
      default:
        ipv4_address: 172.18.0.3
#---Networks-------------------------------------------
networks:
  default:
    driver: bridge
    ipam:
      config:
        -  subnet: 172.18.0.0/16
           gateway: 172.18.0.1
